FROM python:3.14-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY firebase-service-account.json /secrets/firebase.json

COPY . .

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8080"]
